version: '3.9'

services:
  db:
    container_name: db_stageo
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - net_stageo

  phpmyadmin:
    container_name: pma_stageo
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER:admin
      - PMA_PASSWORD:rootpass
    depends_on:
      - db
    networks:
      - net_stageo

  web:
    container_name: apache_stageo
    image: php7.4-apache:projet
    restart: always
    ports:
      # local:container
      - "1337:80"
    environment: 
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - ./www:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - net_stageo
  
networks:
  net_stageo :